<div style="text-align: center;">

<img src="Imagenes/logo.png" alt="Escudo Universidad Nacional de Colombia" width="150"/>

# Tarea 1

**Ardila Otero, María Paula**  
**Cañavera Aluma, Mateo**  
**Martin Acosta, David Esteban**  


---

**3006886: Análisis Numérico**  
**Departamento de Matemáticas**  
**Universidad Nacional de Colombia**

---

**Diciembre 6, 2024**

</div>

# Tabla de contenidos
- [Método del Polinomio Característico](#1-metodo-del-polinomio-caracteristico)
  - [Teoría](#11-teoria)
  - [Análisis del error](#12-analisis-del-error)
  - [Código](#13-codigo)
  - [Testeo](#14-testeo)
- [Método de las Potencias](#2-metodo-de-las-potencias)
  - [Teoría](#21-teoria)
  - [Análisis del error](#22-analisis-del-error)
  - [Código](#23-codigo)
  - [Testeo](#24-testeo)
- [Método de Descomposición QR](#3-metodo-de-descomposicion-qr)
  - [Teoría](#31-teoria)
  - [Análisis del error](#32-analisis-del-error)
  - [Código](#33-codigo)
  - [Testeo](#34-testeo)


# 1. Metodo del polinomio caracteristico

## 1.1 Teoria

## 1.2 Analisis del error

## 1.3 Codigo

## 1.4 Testeo

# 2. Metodo de las potencias

## 2.1 Teoria

El método más simple para calcular los valores y vectores propios de una matriz es el método de las potencias. En la práctica, este método se usa para calcular algunos (no todos) valores propios extremos/dominantes (Allaire & Kaber, 2008, p. 194), es decir el mayor valor (en valor absoluto) que tiene el valor propio de la matriz. 

Lyche (2020, p. 335-337) explica el método de las potencias de la siguiente manera:

Definimos una secuencia de vectores en $\mathbb{C}^n$ mediante:
$$
z_k := A^k z_0 = A z_{k-1}, \quad k = 1, 2, \ldots. \tag{15.1}
$$

Ejemplo 15.1 (Método de las Potencias):
Sea:
$$
A = \begin{bmatrix} 
2 & -1 \\ 
-1 & 2 
\end{bmatrix}, \quad 
z_0 := \begin{bmatrix} 
1 \\ 
0 
\end{bmatrix}.
$$

Calculamos:
$$
z_1 = A z_0 = \begin{bmatrix} 
2 \\ 
-1 
\end{bmatrix}, \quad 
z_2 = A z_1 = \begin{bmatrix} 
5 \\ 
-4 
\end{bmatrix}, \quad \ldots, \quad
z_k = \frac{1}{2} \begin{bmatrix} 
1 + 3^k \\ 
1 - 3^k 
\end{bmatrix}, \ldots
$$

De esto se sigue que $2 z_k / 3^k$ converge a $[1, -1]^T$, un vector propio correspondiente al valor propio dominante $\lambda = 3$.

Para comprender mejor lo que sucede, expandimos $z_0$ en términos de los vectores propios:
$$
z_0 = \frac{1}{2} \begin{bmatrix} 
1 \\ 
-1 
\end{bmatrix} + \frac{1}{2} \begin{bmatrix} 
1 \\ 
1 
\end{bmatrix} = c_1 v_1 + c_2 v_2.
$$

Dado que $A^k$ tiene pares propios $(\lambda_j^k, v_j)$, $j = 1, 2$, encontramos que:
$$
z_k = c_1 \lambda_1^k v_1 + c_2 \lambda_2^k v_2 = c_1 3^k v_1 + c_2 1^k v_2
$$

Por lo tanto:
$$
3^{-k} z_k = c_1 v_1 + 3^{-k} c_2 v_2 \to c_1 v_1.
$$

Dado que $c_1 \neq 0$, obtenemos convergencia hacia el vector propio dominante.

Sea $A \in \mathbb{C}^{n \times n}$ con pares propios $(\lambda_j, v_j)$, $j = 1, \ldots, n$, tales que $|\lambda_1| > |\lambda_2| \geq \ldots \geq |\lambda_n|$. Dado $z_0 \in \mathbb{C}^n$, asumimos que:

(15.2)

(i) $|\lambda_1| > |\lambda_2| \geq |\lambda_3| \geq \ldots \geq |\lambda_n|.$

(ii) $z_0^T v_1 \neq 0.$

(iii) A tiene vectores propios linealmente independientes.

La primera suposición significa que $A$ tiene un valor propio dominante $\lambda_1$ de multiplicidad algebraica uno. La segunda suposición dice que $z_0$ tiene un componente en la dirección de $v_1$. La tercera suposición no es estrictamente necesaria, pero se incluye para simplificar el análisis.

Para observar qué sucede, sea:
$$
z_0 = c_1 v_1 + c_2 v_2 + \cdots + c_n v_n,
$$
donde por la suposición (ii) de $(15.2)$, tenemos $c_1 \neq 0$. Como $A^k v_j = \lambda_j^k v_j$ para todo $j$, vemos que:
$$
z_k = c_1 \lambda_1^k v_1 + c_2 \lambda_2^k v_2 + \cdots + c_n \lambda_n^k v_n, \quad k = 0, 1, 2, \ldots. \tag{15.3}
$$

Dividiendo por $\lambda_1^k$, obtenemos:
$$
\frac{z_k}{\lambda_1^k} = c_1 v_1 + c_2 \left(\frac{\lambda_2}{\lambda_1}\right)^k v_2 + \cdots + c_n \left(\frac{\lambda_n}{\lambda_1}\right)^k v_n, \quad k = 0, 1, 2, \ldots. \tag{15.4}
$$

La suposición (i) de $(15.2)$ implica que $(\lambda_j / \lambda_1)^k \to 0$ cuando $k \to \infty$ para todo $j \geq 2$, y obtenemos:
$$
\lim_{k \to \infty} \frac{z_k}{\lambda_1^k} = c_1 v_1. \tag{15.5}
$$

Ahora, Wendland (2017, p. 152)

El último término es un vector propio de $A$ asociado al valor propio $\lambda_1$. Sin embargo, esto es de uso limitado, ya que no conocemos el valor propio $\lambda_1$ y, por lo tanto, no podemos formar el cociente $A^m x / \lambda_1^m$. Otro problema surge del hecho de que la norma de $A^m x$ converge a cero si $|\lambda_1| < 1$ y tiende a infinito si $|\lambda_1| > 1$. Ambos problemas se resuelven mediante la normalización. Por ejemplo, si tomamos la norma euclidiana de $A^m x$, entonces:
$$
\|A^m x\|_2 = \left( \sum_{i,j=1}^n c_i c_j \lambda_i^m \lambda_j^m w_i^T w_j \right)^{1/2} =: |\lambda_1|^m \left( |c_1| \|w_1\|_2 + r_m \right), \tag{5.13}
$$
donde $r_m \to 0$ cuando $m \to \infty$. A partir de esto podemos concluir que:
$$
\frac{\|A^{m+1} x\|_2}{\|A^m x\|_2} = \frac{\|A^m x\|_2 |\lambda_1|^{m+1}}{\|A^m x\|_2 |\lambda_1|^m} \to |\lambda_1|, \quad m \to \infty. \tag{5.14}
$$

Esto nos proporciona $\lambda_1$ hasta su signo. Para determinar también su signo y un vector propio correspondiente, refinamos el método como sigue.






## 2.2 Analisis del error

## 2.3 Codigo

## 2.4 Testeo

# 3. Metodo QR 

## 3.1 Teoria

## Evitar Confusiones : QR Algorithm vs QR Decomposition

El algoritmo QR utiliza algo llamado descomposición QR. Ambos son importantes, así que no los confunda.
La descomposición QR descompone una matriz A=QR en un conjunto de columnas ortonormales Q y una matriz triangular R. 


## INTRODUCCIÓN

El **proceso de Gram-Schmidt** genera una base ortonormal a partir de un conjunto de vectores base de un espacio vectorial. Como tal, genera una base alternativa para un espacio. La representación matricial de esta base ortonormal se denota como $ Q $. Junto con la matriz triangular superior $ R $, se obtiene una descomposición de una matriz $ A$ , tal que:$A$ = $Q$ $R$

En este notebook, utilizamos un ejemplo para comprender este proceso de cambio de base, así como la descomposición QR. Usaremos la librería **SymPy** para demostrar el proceso.


## Paquetes que usaremos en este apartado

In [30]:
from sympy import Matrix, init_printing
init_printing() # Genera las impresiones en formato LateX en pantalla

Este es el proceso que determina la matriz $ Q $ en la descomposición $QR$. $Q$ es una matriz ortonormal, es decir, todos los vectores columna son ortogonales entre sí y tienen longitud unitaria (normalizados).

Consideramos tres vectores columna en una matriz, mostrados en la ecuación (1):

$$
A = 
\begin{pmatrix}
1 & 0 & 0 \\
1 & 1 & 0 \\
1 & 1 & 1
\end{pmatrix}
\tag{1}
$$

La función `Matrix` del paquete SymPy se utiliza para crear esta matriz, junto con el método `reshape` para organizar sus elementos en filas y columnas. Los elementos de la matriz se ingresan fila por fila.


In [57]:
A = Matrix([1, 0, 0, 1, 1, 0, 1, 1, 1]).reshape(3, 3)
A

⎡1  0  0⎤
⎢       ⎥
⎢1  1  0⎥
⎢       ⎥
⎣1  1  1⎦

### Verificación de independencia lineal y descomposición QR usando SymPy

Los tres vectores columna son linealmente independientes y abarcan un espacio de dimensión 3. Podemos verificar esto al observar la **forma escalonada reducida (RREF)** de la matriz. Esto se hace utilizando el método `rref()`, que está disponible para un objeto matriz creado usando la función `Matrix` del paquete SymPy.

In [58]:
A.rref()

⎛⎡1  0  0⎤           ⎞
⎜⎢       ⎥           ⎟
⎜⎢0  1  0⎥, (0, 1, 2)⎟
⎜⎢       ⎥           ⎟
⎝⎣0  0  1⎦           ⎠

También podemos usar `rank` y ver que nos retorna un valor 3.

In [59]:
A.rank()

El método `QRdecomposition` de SymPy nos permite realizar la descomposición QR de una matriz.

In [124]:
#Usando Sympy
Q, R = Matrix([[1, 0, 0],[ 1, 1, 0],[ 1, 1, 1]]).QRdecomposition()

In [125]:
Q

⎡√3  -√6       ⎤
⎢──  ────   0  ⎥
⎢3    3        ⎥
⎢              ⎥
⎢√3   √6   -√2 ⎥
⎢──   ──   ────⎥
⎢3    6     2  ⎥
⎢              ⎥
⎢√3   √6    √2 ⎥
⎢──   ──    ── ⎥
⎣3    6     2  ⎦

In [126]:
R

⎡    2⋅√3  √3⎤
⎢√3  ────  ──⎥
⎢     3    3 ⎥
⎢            ⎥
⎢     √6   √6⎥
⎢0    ──   ──⎥
⎢     3    6 ⎥
⎢            ⎥
⎢          √2⎥
⎢0    0    ──⎥
⎣          2 ⎦

Verificamos que $QR$ = $A$

In [127]:
Q @ R

⎡1  0  0⎤
⎢       ⎥
⎢1  1  0⎥
⎢       ⎥
⎣1  1  1⎦

En la explicación que sigue, consideramos cada vector columna en $A$ como $\mathbf{a}_i$. Nuestro objetivo es crear una base ortonormal de tres vectores, $\mathbf{u}_i$. Una vez normalizados, los representaremos como $\hat{\mathbf{u}}_i$.

### Paso 1: Selección del primer vector ortonormal


Comenzamos seleccionando uno de los vectores de $A$ como el primero de los vectores de la base ortonormal, $\mathbf{u}_1$. Elegimos $\mathbf{a}_1$ y necesitamos normalizarlo usando la ecuación (2):

$$
\mathbf{u}_1 = \mathbf{a}_1
$$

$$
\hat{\mathbf{u}}_1 = \frac{\mathbf{a}_1}{\|\mathbf{a}_1\|}
$$

In [128]:
# Extraer el primer vector columna de A
a1 = A[:, 0]
a1

⎡1⎤
⎢ ⎥
⎢1⎥
⎢ ⎥
⎣1⎦

In [129]:
# Asignar el primer vector columna a u1
u1 = a1

In [130]:
# Calcular la norma de a1
a1_norm = a1.norm()
a1_norm


In [131]:
# Normalizar el vector u1
u1_normalized = u1 / a1_norm
u1_normalized


⎡√3⎤
⎢──⎥
⎢3 ⎥
⎢  ⎥
⎢√3⎥
⎢──⎥
⎢3 ⎥
⎢  ⎥
⎢√3⎥
⎢──⎥
⎣3 ⎦

### Cálculo de la proyección del vector $\mathbf{a}_2$ sobre $\mathbf{u}_1$


La fórmula para calcular la proyección de un vector $\mathbf{a}_2$ sobre un vector $\mathbf{u}_1$ es:

$$
\text{proj}_{\mathbf{u}_1} \mathbf{a}_2 = \frac{\mathbf{a}_2 \cdot \mathbf{u}_1}{\|\mathbf{u}_1\|^2} \mathbf{u}_1
$$




imagen

In [132]:
a2 = A[:,1] # Extraer el Segundo vector columna A
a2

⎡0⎤
⎢ ⎥
⎢1⎥
⎢ ⎥
⎣1⎦

In [133]:
# Calcular la proyección de a2 sobre u1
projection_u1_a2 = (a1.dot(a2) / u1.norm()**2) * u1
projection_u1_a2


⎡2/3⎤
⎢   ⎥
⎢2/3⎥
⎢   ⎥
⎣2/3⎦



Convenientemente, la proyección de $\mathbf{a}_2$ sobre $\mathbf{u}_1$ es ortogonal, lo que nos permite derivar $\mathbf{u}_2$. Encontramos que:

$$
\mathbf{u}_2 + \text{proj}_{\mathbf{u}_1} \mathbf{a}_2 = \mathbf{a}_2 + \frac{\mathbf{a}_2 \cdot \mathbf{u}_1}{\|\mathbf{u}_1\|^2} \mathbf{u}_1
$$

Por lo tanto, podemos calcular $\mathbf{u}_2$ usando:

$$
\mathbf{u}_2 = \mathbf{a}_2 - \frac{\mathbf{a}_2 \cdot \mathbf{u}_1}{\|\mathbf{u}_1\|^2} \mathbf{u}_1
$$




In [134]:
#Creacion de u2 como se presentó arriba
u2 = a2 - projection_u1_a2
u2

⎡-2/3⎤
⎢    ⎥
⎢1/3 ⎥
⎢    ⎥
⎣1/3 ⎦

normalizamos $\mathbf{u}_2$ para obtener  $\hat{\mathbf{u}}_2$

In [135]:

u2_normalized = u2 / u2.norm()
u2_normalized


⎡-√6 ⎤
⎢────⎥
⎢ 3  ⎥
⎢    ⎥
⎢ √6 ⎥
⎢ ── ⎥
⎢ 6  ⎥
⎢    ⎥
⎢ √6 ⎥
⎢ ── ⎥
⎣ 6  ⎦

### Cálculo del vector $\mathbf{u}_3$

El vector $\mathbf{u}_3$ debe ser ortogonal tanto a $\mathbf{u}_2$ como a $\mathbf{u}_1$. De hecho, podemos ampliar la fórmula en (4) y usar (5) para cualquier vector ortogonal arbitrario $\mathbf{u}_i$:

$$
\mathbf{u}_n = \mathbf{a}_n - \sum_{i=1}^{n-1} \frac{\mathbf{a}_n \cdot \mathbf{u}_i}{\|\mathbf{u}_i\|^2} \mathbf{u}_i
\tag{5}
$$

Para la suma mostrada en (5), necesitamos calcular dos proyecciones, como se muestra en (6):

$$
\text{proj}_{\mathbf{u}_2} \mathbf{a}_3 = \frac{\mathbf{a}_3 \cdot \mathbf{u}_2}{\|\mathbf{u}_2\|^2} \mathbf{u}_2
$$

$$
\text{proj}_{\mathbf{u}_1} \mathbf{a}_3 = \frac{\mathbf{a}_3 \cdot \mathbf{u}_1}{\|\mathbf{u}_1\|^2} \mathbf{u}_1
\tag{6}
$$

El tercer vector columna, $\mathbf{a}_3$, es extraído de la matriz $A$ y las proyecciones sobre $\mathbf{u}_1$ y $\mathbf{u}_2$ son calculadas.


In [136]:
a3 = A[:, 2]
a3


⎡0⎤
⎢ ⎥
⎢0⎥
⎢ ⎥
⎣1⎦

In [137]:
proj_u2_a3 = (a3.dot(u2) / (u2.norm()**2)) * u2
proj_u2_a3


⎡-1/3⎤
⎢    ⎥
⎢1/6 ⎥
⎢    ⎥
⎣1/6 ⎦

In [138]:
proj_u1_a3 = (a3.dot(u1) / (u1.norm()**2)) * u1
proj_u1_a3


⎡1/3⎤
⎢   ⎥
⎢1/3⎥
⎢   ⎥
⎣1/3⎦

En (7), expandimos la suma mostrada en (5):

$$
\mathbf{u}_3 + \text{proj}_{\mathbf{u}_2} \mathbf{a}_3 + \text{proj}_{\mathbf{u}_1} \mathbf{a}_3 = \mathbf{a}_3
$$

$$
\mathbf{u}_3 = \mathbf{a}_3 - \frac{\mathbf{a}_3 \cdot \mathbf{u}_2}{\|\mathbf{u}_2\|^2} \mathbf{u}_2 - \frac{\mathbf{a}_3 \cdot \mathbf{u}_1}{\|\mathbf{u}_1\|^2} \mathbf{u}_1
$$

In [139]:
u3 = a3 - proj_u2_a3 - proj_u1_a3
u3

⎡ 0  ⎤
⎢    ⎥
⎢-1/2⎥
⎢    ⎥
⎣1/2 ⎦

normalizamos $\mathbf{u}_3$ para obtener  $\hat{\mathbf{u}}_3$

In [140]:
u3_normalized = u3 / u3.norm()
u3_normalized


⎡ 0  ⎤
⎢    ⎥
⎢-√2 ⎥
⎢────⎥
⎢ 2  ⎥
⎢    ⎥
⎢ √2 ⎥
⎢ ── ⎥
⎣ 2  ⎦

combinamos los tres vectores ortonormales $\hat{\mathbf{u}}$ y obtenemos una matriz $Q$:


u_hat = Matrix([u1_normalized, u2_normalized, u3_normalized]).reshape(3, 3).transpose()
u_hat

In [121]:
u1_normalized.dot(u2_normalized)  # Debe ser 0

In [122]:
u1_normalized.dot(u3_normalized)  # Debe ser 0

In [119]:
u2_normalized.dot(u3_normalized)  # Debe ser 0

## _QR_ DECOMPOSITION

Todavía necesitamos calcular la matriz $\mathbf{R}$. La forma de $\mathbf{R}$ se muestra en (8):

$$
\mathbf{R} =
\begin{pmatrix}
\mathbf{a}_1 \cdot \hat{\mathbf{u}}_1 & \mathbf{a}_2 \cdot \hat{\mathbf{u}}_1 & \mathbf{a}_3 \cdot \hat{\mathbf{u}}_1 \\
0 & \mathbf{a}_2 \cdot \hat{\mathbf{u}}_2 & \mathbf{a}_3 \cdot \hat{\mathbf{u}}_2 \\
0 & 0 & \mathbf{a}_3 \cdot \hat{\mathbf{u}}_3
\end{pmatrix}
$$


In [123]:
R = Matrix([
    [a1.dot(u1_normalized), a2.dot(u1_normalized), a3.dot(u1_normalized)],
    [0, a2.dot(u2_normalized), a3.dot(u2_normalized)],
    [0, 0, a3.dot(u3_normalized)]
])
R


⎡    2⋅√3  √3⎤
⎢√3  ────  ──⎥
⎢     3    3 ⎥
⎢            ⎥
⎢     √6   √6⎥
⎢0    ──   ──⎥
⎢     3    6 ⎥
⎢            ⎥
⎢          √2⎥
⎢0    0    ──⎥
⎣          2 ⎦

## Conclusión

La descomposición $QR$ se utiliza en muchos algoritmos numéricos, como la determinación de los valores propios de matrices grandes.

Aunque hemos utilizado el caso simple del producto punto, la ortonormalización y la descomposición $QR$ se describen para espacios de producto interno general. Por lo tanto, volvemos a los resultados mostrados en (5) y (8), presentados aquí como (9) y (10).

$$
\mathbf{u}_n = \mathbf{a}_n - \sum_{i=1}^{n-1} \frac{\langle \mathbf{a}_n, \mathbf{u}_i \rangle}{\|\mathbf{u}_i\|^2} \mathbf{u}_i
\tag{9}
$$

$$
\mathbf{R} =
\begin{pmatrix}
\langle \mathbf{a}_1, \hat{\mathbf{u}}_1 \rangle & \langle \mathbf{a}_2, \hat{\mathbf{u}}_1 \rangle & \langle \mathbf{a}_3, \hat{\mathbf{u}}_1 \rangle \\
0 & \langle \mathbf{a}_2, \hat{\mathbf{u}}_2 \rangle & \langle \mathbf{a}_3, \hat{\mathbf{u}}_2 \rangle \\
0 & 0 & \langle \mathbf{a}_3, \hat{\mathbf{u}}_3 \rangle
\end{pmatrix}
\tag{10}
$$

## 3.2 Analisis del error

En esta sección, se analizarán los errores introducidos en los cálculos del algoritmo QR y cómo estos afectan la convergencia del algoritmo y los resultados finales.

#### Desventaja 1: Costo Computacional

Un paso del método QR básico es relativamente costoso. Más precisamente,La complejidad de un paso del método $QR$ básico es $ O(n^3) $.

Por lo tanto, incluso en una situación excesivamente optimista donde el número de pasos fuera proporcional a  $n$, el algoritmo necesitaría $ O(n^4) $ operaciones.



En los Test que se realizaron, podemos ver las matrices F, G, H al aplicarles el algoritmo QR, la matriz que retorna el algoritmo no logra convertirse en matriz triangular, por lo que los auto valores y vectores no logran ser precisos.

#### Desventaja 2:
el método QR básico puede ser arbitrariamente lento si los valores propios están muy cerca unos de otros. En la práctica, suele ser lento.

## 3.3 Codigo
### El algoritmo QR



![QR_ALGO](Imagenes/QRALGO.png)


el algoritmo funciona simultaneamente para p = n




In [305]:
import numpy as np

def QR_Decomposition(matrix_A):
    # Obtener las dimensiones de la matriz A (n x m), donde n es el número de filas y m el número de columnas
    num_rows, num_columns = matrix_A.shape  # num_rows es el número de filas, num_columns es el número de columnas
    
    # Inicializamos las matrices Q y u
    Q = np.empty((num_rows, num_rows))  # Matriz Q tiene el mismo número de filas que matrix_A y num_rows columnas
    u = np.empty((num_rows, num_rows))  # Matriz u almacena los vectores intermedios en el proceso de ortogonalización

    # Paso 1: Definir el primer vector ortogonal
    u[:, 0] = matrix_A[:, 0]  # Tomamos la primera columna de matrix_A como el primer vector u_1
    Q[:, 0] = u[:, 0] / np.linalg.norm(u[:, 0])  # Normalizamos el primer vector u_1 para obtener el primer vector ortonormal q_1

    # Paso 2: Para cada columna posterior de matrix_A, hacer ortogonalización y normalización
    for column_index in range(1, num_rows):
        # Paso 2.1: Inicializamos el vector u correspondiente a la columna actual de matrix_A
        u[:, column_index] = matrix_A[:, column_index]
        
        # Paso 2.2: Restamos las proyecciones de los vectores anteriores de Q para ortogonalizar el vector u
        for previous_vector_index in range(column_index):
            u[:, column_index] -= (matrix_A[:, column_index] @ Q[:, previous_vector_index]) * Q[:, previous_vector_index]
        
        # Paso 2.3: Normalizamos el nuevo vector ortogonal u para obtener el siguiente vector ortonormal q
        Q[:, column_index] = u[:, column_index] / np.linalg.norm(u[:, column_index])

    # Paso 3: Calculamos la matriz R, que es triangular superior
    R = np.zeros((num_rows, num_columns))  # Inicializamos la matriz R con ceros
    
    # Paso 3.1: Calculamos los elementos de R como el producto escalar entre las columnas de matrix_A y los vectores de Q
    for row_index in range(num_rows):
        for column_index in range(row_index, num_columns):
            R[row_index, column_index] = matrix_A[:, column_index] @ Q[:, row_index]
    
    # Devolvemos las matrices Q y R
    return Q, R


In [307]:
def pure_qr(A, max_iter=2000):
    # Copiamos la matriz de entrada A para no modificar la original
    Ak = np.copy(A)
    
    # Obtenemos el tamaño de la matriz (asumimos que es cuadrada)
    n = A.shape[0]
    
    # Inicializamos la matriz Q como la identidad, que es el valor inicial de la matriz ortogonal
    QQ = np.eye(n)

    # Iniciamos el ciclo de iteraciones
    for k in range(max_iter+1):
        # Aplicamos la descomposición QR a la matriz Ak
        Q, R = QR_Decomposition(Ak)
        
        # Actualizamos Ak como el producto R @ Q
        Ak = R @ Q
        
        # Multiplicamos la matriz Q actualizada a la matriz QQ
        QQ = QQ @ Q
        
        # Imprimimos el estado de Ak y QQ cada 100 iteraciones para monitorear el progreso
        if k % 200 == 0:
            print("Iteración:", k)
            print("(matriz actualizada):")
            print(Ak)
            print("\n")

    # Después de max_iter iteraciones, devolvemos la matriz Ak y la matriz ortogonal QQ
    return  Ak, QQ


## 3.4 Testeo

In [308]:
import numpy as np

In [309]:
# Matrices Test Tarea
A = np.array([[2, 1],
              [3, 4]])

B = np.array([[3, 2],
              [3, 4]])

C = np.array([[2, 3],
              [1, 4]])

D = np.array([[1, 1, 1],
              [2, 1, 1],
              [1, 1, 3]])

E = np.array([[1, 1, 2],
              [2, 1, 3],
              [1, 1, 1]])

F = np.array([[2, 1, 2],
              [1, 1, 3],
              [1, 1, 1]])

G = np.array([[1, 1, 1, 1],
              [1, 2, 1, 2],
              [2, 1, 1, 1],
              [2, 1, 1, 4]])

H = np.array([[1, 1, 1, 2],
              [2, 1, 1, 2],
              [1, 1, 1, 4],
              [2, 1, 1, 4]])


In [321]:
Ak, QQ_a = pure_qr(A)
QQ_a

Iteración: 0
(matriz actualizada):
[[ 5.23076923 -0.84615385]
 [ 1.15384615  0.76923077]]


Iteración: 200
(matriz actualizada):
[[ 5.00000000e+000 -2.00000000e+000]
 [ 1.54266052e-140  1.00000000e+000]]


Iteración: 400
(matriz actualizada):
[[ 5.00000000e+000 -2.00000000e+000]
 [ 2.47895988e-280  1.00000000e+000]]


Iteración: 600
(matriz actualizada):
[[ 5. -2.]
 [ 0.  1.]]


Iteración: 800
(matriz actualizada):
[[ 5. -2.]
 [ 0.  1.]]


Iteración: 1000
(matriz actualizada):
[[ 5. -2.]
 [ 0.  1.]]


Iteración: 1200
(matriz actualizada):
[[ 5. -2.]
 [ 0.  1.]]


Iteración: 1400
(matriz actualizada):
[[ 5. -2.]
 [ 0.  1.]]


Iteración: 1600
(matriz actualizada):
[[ 5. -2.]
 [ 0.  1.]]


Iteración: 1800
(matriz actualizada):
[[ 5. -2.]
 [ 0.  1.]]


Iteración: 2000
(matriz actualizada):
[[ 5. -2.]
 [ 0.  1.]]




array([[ 0.31622777, -0.9486833 ],
       [ 0.9486833 ,  0.31622777]])

In [312]:
#COMPARACION CON NUMPY
eigenvalores, eigenvectores = np.linalg.eig(A)

# Mostrar los resultados
print("Eigenvalores:")
print(eigenvalores)
print("\nEigenvectores:")
print(eigenvectores)

Eigenvalores:
[1. 5.]

Eigenvectores:
[[-0.70710678 -0.31622777]
 [ 0.70710678 -0.9486833 ]]


In [313]:
Bk, QQ_b = pure_qr(B)
QB

Iteración: 0
(matriz actualizada):
[[ 6.00000000e+00 -2.66453526e-15]
 [ 1.00000000e+00  1.00000000e+00]]


Iteración: 200
(matriz actualizada):
[[ 6.0000000e+000 -1.0000000e+000]
 [ 2.2527686e-156  1.0000000e+000]]


Iteración: 400
(matriz actualizada):
[[ 6.00000000e+000 -1.00000000e+000]
 [ 5.27796502e-312  1.00000000e+000]]


Iteración: 600
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 800
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 1000
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 1200
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 1400
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 1600
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 1800
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 2000
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]




array([[ 0.5547002 , -0.83205029],
       [ 0.83205029,  0.5547002 ]])

In [314]:
#COMPARACION CON NUMPY
eigenvalores, eigenvectores = np.linalg.eig(B)

# Mostrar los resultados
print("Eigenvalores:")
print(eigenvalores)
print("\nEigenvectores:")
print(eigenvectores) 

Eigenvalores:
[1. 6.]

Eigenvectores:
[[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]


In [315]:
Bk, QQ_b = pure_qr(B)
QQ_b

Iteración: 0
(matriz actualizada):
[[ 6.00000000e+00 -2.66453526e-15]
 [ 1.00000000e+00  1.00000000e+00]]


Iteración: 200
(matriz actualizada):
[[ 6.0000000e+000 -1.0000000e+000]
 [ 2.2527686e-156  1.0000000e+000]]


Iteración: 400
(matriz actualizada):
[[ 6.00000000e+000 -1.00000000e+000]
 [ 5.27796502e-312  1.00000000e+000]]


Iteración: 600
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 800
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 1000
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 1200
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 1400
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 1600
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 1800
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 2000
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]




array([[ 0.5547002 , -0.83205029],
       [ 0.83205029,  0.5547002 ]])

In [316]:
Ck, QQ_c = pure_qr(C)
QQ_c

Iteración: 0
(matriz actualizada):
[[4. 3.]
 [1. 2.]]


Iteración: 200
(matriz actualizada):
[[5.00000000e+000 2.00000000e+000]
 [2.57110087e-140 1.00000000e+000]]


Iteración: 400
(matriz actualizada):
[[5.0000000e+000 2.0000000e+000]
 [4.1315998e-280 1.0000000e+000]]


Iteración: 600
(matriz actualizada):
[[5. 2.]
 [0. 1.]]


Iteración: 800
(matriz actualizada):
[[5. 2.]
 [0. 1.]]


Iteración: 1000
(matriz actualizada):
[[5. 2.]
 [0. 1.]]


Iteración: 1200
(matriz actualizada):
[[5. 2.]
 [0. 1.]]


Iteración: 1400
(matriz actualizada):
[[5. 2.]
 [0. 1.]]


Iteración: 1600
(matriz actualizada):
[[5. 2.]
 [0. 1.]]


Iteración: 1800
(matriz actualizada):
[[5. 2.]
 [0. 1.]]


Iteración: 2000
(matriz actualizada):
[[5. 2.]
 [0. 1.]]




array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [317]:
#COMPARACION CON NUMPY
eigenvalores, eigenvectores = np.linalg.eig(C)

# Mostrar los resultados
print("Eigenvalores:")
print(eigenvalores)
print("\nEigenvectores:")
print(eigenvectores) 

Eigenvalores:
[1. 5.]

Eigenvectores:
[[-0.9486833  -0.70710678]
 [ 0.31622777 -0.70710678]]


In [318]:
Dk, QQ_d = pure_qr(D)
QQ_d

Iteración: 0
(matriz actualizada):
[[3.33333333e+00 1.88561808e+00 4.21884749e-15]
 [1.17851130e+00 6.66666667e-01 1.22474487e+00]
 [5.77350269e-01 8.16496581e-01 1.00000000e+00]]


Iteración: 200
(matriz actualizada):
[[ 4.16424794e+000  8.81780589e-002 -6.31615086e-001]
 [ 9.88413594e-107  1.22713444e+000  7.70251267e-001]
 [ 7.80854598e-206  1.75945392e-099 -3.91382381e-001]]


Iteración: 400
(matriz actualizada):
[[ 4.16424794e+000  8.81780589e-002 -6.31615086e-001]
 [ 7.34601761e-213  1.22713444e+000  7.70251267e-001]
 [ 0.00000000e+000  9.70963425e-199 -3.91382381e-001]]


Iteración: 600
(matriz actualizada):
[[ 4.16424794e+000  8.81780589e-002 -6.31615086e-001]
 [ 5.45967242e-319  1.22713444e+000  7.70251267e-001]
 [ 0.00000000e+000  5.35831012e-298 -3.91382381e-001]]


Iteración: 800
(matriz actualizada):
[[ 4.16424794  0.08817806 -0.63161509]
 [ 0.          1.22713444  0.77025127]
 [ 0.          0.         -0.39138238]]


Iteración: 1000
(matriz actualizada):
[[ 4.16424794  0.

array([[ 0.40031591, -0.37121716, -0.83782157],
       [ 0.49644754, -0.68063221,  0.53877606],
       [ 0.77025127,  0.63161509,  0.08817806]])

In [319]:
#COMPARACION CON NUMPY
eigenvalores, eigenvectores = np.linalg.eig(D)

# Mostrar los resultados
print("Eigenvalores:")
print(eigenvalores)
print("\nEigenvectores:")
print(eigenvectores) 

Eigenvalores:
[ 4.16424794 -0.39138238  1.22713444]

Eigenvectores:
[[-0.40031591 -0.53877606 -0.38306286]
 [-0.49644754  0.83782157 -0.69522332]
 [-0.77025127 -0.08817806  0.60821655]]


In [320]:
Ek, QQ_e = pure_qr(E)
QQ_e

Iteración: 0
(matriz actualizada):
[[ 3.83333333e+00  2.59272486e+00 -8.66025404e-01]
 [ 4.71404521e-01 -3.33333333e-01 -7.09894518e-17]
 [ 2.88675135e-01  4.08248290e-01 -5.00000000e-01]]


Iteración: 200
(matriz actualizada):
[[ 4.04891734e+000  2.39475083e+000  4.98818945e-001]
 [ 1.43776605e-154 -6.92021472e-001 -1.27859767e-001]
 [ 3.26125182e-212  6.98580645e-059 -3.56895868e-001]]


Iteración: 400
(matriz actualizada):
[[ 4.04891734e+000  2.39475083e+000  4.98818945e-001]
 [ 5.17392413e-308 -6.92021472e-001 -1.27859767e-001]
 [ 0.00000000e+000  2.13111341e-116 -3.56895868e-001]]


Iteración: 600
(matriz actualizada):
[[ 4.04891734e+000  2.39475083e+000  4.98818945e-001]
 [ 0.00000000e+000 -6.92021472e-001 -1.27859767e-001]
 [ 0.00000000e+000  6.50124564e-174 -3.56895868e-001]]


Iteración: 800
(matriz actualizada):
[[ 4.04891734e+000  2.39475083e+000  4.98818945e-001]
 [ 0.00000000e+000 -6.92021472e-001 -1.27859767e-001]
 [ 0.00000000e+000  1.98329167e-231 -3.56895868e-001]]


I

array([[ 0.51769363, -0.03900114,  0.85467668],
       [ 0.74808896, -0.46410467, -0.47430977],
       [ 0.41515805,  0.88492134, -0.21108771]])

In [300]:
#COMPARACION CON NUMPY
eigenvalores, eigenvectores = np.linalg.eig(E)

# Mostrar los resultados
print("Eigenvalores:")
print(eigenvalores)
print("\nEigenvectores:")
print(eigenvectores) 

Eigenvalores:
[ 4.04891734 -0.35689587 -0.69202147]

Eigenvectores:
[[-0.51769363 -0.85467668 -0.26822309]
 [-0.74808896  0.21108771 -0.75154439]
 [-0.41515805  0.47430977  0.6026918 ]]


In [301]:
Fk, QQ_f = pure_qr(F)
QQ_f

Iteración: 0
(matriz actualizada):
[[ 4.          1.41421356 -1.15470054]
 [ 0.70710678  1.         -0.40824829]
 [ 0.57735027  0.81649658 -1.        ]]


Iteración: 200
(matriz actualizada):
[[ 4.12488542e+000  1.83902152e+000  1.03502220e+000]
 [-5.55451060e-148 -7.61557182e-001 -7.39411184e-001]
 [ 7.22787913e-163  9.90986182e-016  6.36671762e-001]]


Iteración: 400
(matriz actualizada):
[[ 4.12488542e+000  1.83902152e+000  1.03502220e+000]
 [-1.00640214e-294 -7.61557182e-001 -7.39411184e-001]
 [ 0.00000000e+000  2.74588055e-031  6.36671762e-001]]


Iteración: 600
(matriz actualizada):
[[ 4.12488542e+00  1.83902152e+00  1.03502220e+00]
 [ 0.00000000e+00 -7.61557182e-01 -7.39411184e-01]
 [ 0.00000000e+00  7.60844107e-47  6.36671762e-01]]


Iteración: 800
(matriz actualizada):
[[ 4.12488542e+00  1.83902152e+00  1.03502220e+00]
 [ 0.00000000e+00 -7.61557182e-01 -7.39411184e-01]
 [ 0.00000000e+00  2.10818987e-62  6.36671762e-01]]


Iteración: 1000
(matriz actualizada):
[[ 4.12488542e+00

array([[ 0.67550236,  0.17865763, -0.71538662],
       [ 0.61159354, -0.67770693,  0.40824829],
       [ 0.41188579,  0.71329852,  0.56705848]])

In [282]:
#COMPARACION CON NUMPY
eigenvalores, eigenvectores = np.linalg.eig(F)

# Mostrar los resultados
print("Eigenvalores:")
print(eigenvalores)
print("\nEigenvectores:")
print(eigenvectores) 

Eigenvalores:
[ 4.12488542  0.63667176 -0.76155718]

Eigenvectores:
[[-0.67550236 -0.72653358 -0.07072589]
 [-0.61159354  0.66793428 -0.84969749]
 [-0.41188579  0.16128473  0.52250553]]


In [302]:
Gk, QQ_g = pure_qr(G)
QQ_g

Iteración: 0
(matriz actualizada):
[[ 5.5         0.98198051  1.3174651   1.56524758]
 [ 1.2001984   0.97619048 -0.62822862  0.048795  ]
 [-0.09759001  0.04259177  0.02380952 -0.54554473]
 [ 1.34164079 -0.58554004 -0.32732684  1.5       ]]


Iteración: 200
(matriz actualizada):
[[ 6.09964773e+000  1.52542362e-001  6.41103498e-001  1.17035971e+000]
 [ 3.83687961e-136  1.28353694e+000 -7.64983465e-001  3.31678699e-001]
 [-3.82487504e-158  2.15785803e-023  1.00000000e+000  7.07647380e-001]
 [ 9.37258329e-241 -5.28767710e-106 -2.45042863e-083 -3.83184672e-001]]


Iteración: 400
(matriz actualizada):
[[ 6.09964773e+000  1.52542362e-001  6.41103498e-001  1.17035971e+000]
 [ 1.60214531e-271  1.28353694e+000 -7.64983465e-001  3.31678699e-001]
 [-3.32404143e-315  4.49105438e-045  1.00000000e+000  7.07647380e-001]
 [ 0.00000000e+000 -5.28708070e-211 -1.17724709e-166 -3.83184672e-001]]


Iteración: 600
(matriz actualizada):
[[ 6.09964773e+000  1.52542362e-001  6.41103498e-001  1.17035971e+000]
 [

array([[ 0.31147039,  0.41960533,  0.02253298,  0.8522968 ],
       [ 0.51244186, -0.05145287, -0.84573836, -0.13957997],
       [ 0.36253406,  0.74044997,  0.25776971, -0.50384291],
       [ 0.71341334, -0.52251106,  0.46666227, -0.01580904]])

In [303]:
#COMPARACION CON NUMPY
eigenvalores, eigenvectores = np.linalg.eig(G)

# Mostrar los resultados
print("Eigenvalores:")
print(eigenvalores)
print("\nEigenvectores:")
print(eigenvectores) 

Eigenvalores:
[ 6.09964773 -0.38318467  1.          1.28353694]

Eigenvectores:
[[ 0.31147039  0.51356051  0.37796447 -0.40953464]
 [ 0.51244186  0.2099646  -0.37796447  0.06764969]
 [ 0.36253406 -0.82668232  0.75592895 -0.72860193]
 [ 0.71341334 -0.0936313  -0.37796447  0.54483403]]


In [304]:
Hk, QQ_h = pure_qr(H)
QQ_h

Iteración: 0
(matriz actualizada):
[[ 6.4         0.8        -1.46558698 -0.34783765]
 [ 1.8        -0.4         0.20936957  0.75817737]
 [-1.83198373  0.26171196 -0.06849315 -1.09168807]
 [-0.42936209  0.21468105 -0.16855379 -0.34420116]]


Iteración: 200
(matriz actualizada):
[[ 7.17748574e+000 -3.94520684e+000  2.34347439e+000 -4.08075588e+000]
 [ 4.55895088e-090 -2.55815017e+000  9.85243001e-002 -9.08555088e-001]
 [ 0.00000000e+000  2.91888089e-304 -3.16007520e-003 -2.84626655e-001]
 [ 0.00000000e+000 -2.28532507e-305  1.94828330e-002 -6.52473972e-002]]


Iteración: 400
(matriz actualizada):
[[ 7.17748574e+000 -3.94520684e+000  3.58030781e+000 -3.05382330e+000]
 [ 1.12099696e-179 -2.55815017e+000  3.98594302e-001 -8.22375807e-001]
 [ 0.00000000e+000  0.00000000e+000  7.38449740e-002 -2.34907002e-001]
 [ 0.00000000e+000  0.00000000e+000  6.92024858e-002 -1.42252446e-001]]


Iteración: 600
(matriz actualizada):
[[ 7.17748574e+000 -3.94520684e+000  1.79707717e+000  4.34913260e+000]
 [

array([[ 0.61021998,  1.16487778, -0.15494665, -0.26550973],
       [ 0.50402139, -0.87309744, -0.15945656,  0.46214147],
       [ 0.59138409,  0.85225356, -0.17336813, -0.07571004],
       [ 0.4851855 , -1.18572166, -0.17787804,  0.65194115]])

In [285]:
#COMPARACION CON NUMPY
eigenvalores, eigenvectores = np.linalg.eig(H)

# Mostrar los resultados
print("Eigenvalores:")
print(eigenvalores)
print("\nEigenvectores:")
print(eigenvectores) 

Eigenvalores:
[ 6.85410197e+00 -3.41870405e-08  3.41870454e-08  1.45898034e-01]

Eigenvectores:
[[ 3.75338235e-01 -2.41738883e-08  2.41738915e-08 -9.17077354e-02]
 [ 4.30099346e-01  7.07106781e-01  7.07106781e-01 -7.20281905e-01]
 [ 5.52548911e-01 -7.07106781e-01 -7.07106781e-01  6.85252667e-01]
 [ 6.07310022e-01  1.20869437e-08 -1.20869462e-08  5.66784975e-02]]
