<div style="text-align: center;">

<img src="https://github.com/macaluzate/Tarea-1-AN-2024/blob/main/Imagenes/logo.png?raw=1" alt="Escudo Universidad Nacional de Colombia" width="150"/>

# Tarea 1

**Ardila Otero, María Paula**  
**Cañavera Aluma, Mateo**  
**Martin Acosta, David Esteban**  


---

**3006886: Análisis Numérico**  
**Departamento de Matemáticas**  
**Universidad Nacional de Colombia**

---

**Diciembre 6, 2024**

</div>

## Código

## El Algoritmo QR

![]()

In [1]:
import numpy as np

def QR_Decomposition(matrix_A):
    # Obtener las dimensiones de la matriz A (n x m), donde n es el número de filas y m el número de columnas
    num_rows, num_columns = matrix_A.shape  # num_rows es el número de filas, num_columns es el número de columnas
    
    # Inicializamos las matrices Q y u
    Q = np.empty((num_rows, num_rows))  # Matriz Q tiene el mismo número de filas que matrix_A y num_rows columnas
    u = np.empty((num_rows, num_rows))  # Matriz u almacena los vectores intermedios en el proceso de ortogonalización

    # Paso 1: Definir el primer vector ortogonal
    u[:, 0] = matrix_A[:, 0]  # Tomamos la primera columna de matrix_A como el primer vector u_1
    Q[:, 0] = u[:, 0] / np.linalg.norm(u[:, 0])  # Normalizamos el primer vector u_1 para obtener el primer vector ortonormal q_1

    # Paso 2: Para cada columna posterior de matrix_A, hacer ortogonalización y normalización
    for column_index in range(1, num_rows):
        # Paso 2.1: Inicializamos el vector u correspondiente a la columna actual de matrix_A
        u[:, column_index] = matrix_A[:, column_index]
        
        # Paso 2.2: Restamos las proyecciones de los vectores anteriores de Q para ortogonalizar el vector u
        for previous_vector_index in range(column_index):
            u[:, column_index] -= (matrix_A[:, column_index] @ Q[:, previous_vector_index]) * Q[:, previous_vector_index]
        
        # Paso 2.3: Normalizamos el nuevo vector ortogonal u para obtener el siguiente vector ortonormal q
        Q[:, column_index] = u[:, column_index] / np.linalg.norm(u[:, column_index])

    # Paso 3: Calculamos la matriz R, que es triangular superior
    R = np.zeros((num_rows, num_columns))  # Inicializamos la matriz R con ceros
    
    # Paso 3.1: Calculamos los elementos de R como el producto escalar entre las columnas de matrix_A y los vectores de Q
    for row_index in range(num_rows):
        for column_index in range(row_index, num_columns):
            R[row_index, column_index] = matrix_A[:, column_index] @ Q[:, row_index]
    
    # Devolvemos las matrices Q y R
    return Q, R


In [2]:
def pure_qr(A, max_iter=2000):
    # Copiamos la matriz de entrada A para no modificar la original
    Ak = np.copy(A)
    
    # Obtenemos el tamaño de la matriz (asumimos que es cuadrada)
    n = A.shape[0]
    
    # Inicializamos la matriz Q como la identidad, que es el valor inicial de la matriz ortogonal
    QQ = np.eye(n)

    # Iniciamos el ciclo de iteraciones
    for k in range(max_iter+1):
        # Aplicamos la descomposición QR a la matriz Ak
        Q, R = QR_Decomposition(Ak)
        
        # Actualizamos Ak como el producto R @ Q
        Ak = R @ Q
        
        # Multiplicamos la matriz Q actualizada a la matriz QQ
        QQ = QQ @ Q
        
        # Imprimimos el estado de Ak y QQ cada 100 iteraciones para monitorear el progreso
        if k % 200 == 0:
            print("Iteración:", k)
            print("(matriz actualizada):")
            print(Ak)
            print("\n")

    # Después de max_iter iteraciones, devolvemos la matriz Ak y la matriz ortogonal QQ
    return  Ak, QQ


### Testeo

In [3]:
# Matrices Test Tarea
A = np.array([[2, 1],
              [3, 4]])

B = np.array([[3, 2],
              [3, 4]])

C = np.array([[2, 3],
              [1, 4]])

D = np.array([[1, 1, 1],
              [2, 1, 1],
              [1, 1, 3]])

E = np.array([[1, 1, 2],
              [2, 1, 3],
              [1, 1, 1]])

F = np.array([[2, 1, 2],
              [1, 1, 3],
              [1, 1, 1]])

G = np.array([[1, 1, 1, 1],
              [1, 2, 1, 2],
              [2, 1, 1, 1],
              [2, 1, 1, 4]])

H = np.array([[1, 1, 1, 2],
              [2, 1, 1, 2],
              [1, 1, 1, 4],
              [2, 1, 1, 4]])


In [4]:
Ak, QQ_a = pure_qr(A)
QQ_a

Iteración: 0
(matriz actualizada):
[[ 5.23076923 -0.84615385]
 [ 1.15384615  0.76923077]]


Iteración: 200
(matriz actualizada):
[[ 5.00000000e+000 -2.00000000e+000]
 [ 1.54266052e-140  1.00000000e+000]]


Iteración: 400
(matriz actualizada):
[[ 5.00000000e+000 -2.00000000e+000]
 [ 2.47895988e-280  1.00000000e+000]]


Iteración: 600
(matriz actualizada):
[[ 5. -2.]
 [ 0.  1.]]


Iteración: 800
(matriz actualizada):
[[ 5. -2.]
 [ 0.  1.]]


Iteración: 1000
(matriz actualizada):
[[ 5. -2.]
 [ 0.  1.]]


Iteración: 1200
(matriz actualizada):
[[ 5. -2.]
 [ 0.  1.]]


Iteración: 1400
(matriz actualizada):
[[ 5. -2.]
 [ 0.  1.]]


Iteración: 1600
(matriz actualizada):
[[ 5. -2.]
 [ 0.  1.]]


Iteración: 1800
(matriz actualizada):
[[ 5. -2.]
 [ 0.  1.]]


Iteración: 2000
(matriz actualizada):
[[ 5. -2.]
 [ 0.  1.]]




array([[ 0.31622777, -0.9486833 ],
       [ 0.9486833 ,  0.31622777]])

In [5]:
#COMPARACION CON NUMPY
eigenvalores, eigenvectores = np.linalg.eig(A)

# Mostrar los resultados
print("Eigenvalores:")
print(eigenvalores)
print("\nEigenvectores:")
print(eigenvectores)

Eigenvalores:
[1. 5.]

Eigenvectores:
[[-0.70710678 -0.31622777]
 [ 0.70710678 -0.9486833 ]]


In [11]:
Bk, QQ_b = pure_qr(B)
QQ_b

Iteración: 0
(matriz actualizada):
[[ 6.00000000e+00 -2.66453526e-15]
 [ 1.00000000e+00  1.00000000e+00]]


Iteración: 200
(matriz actualizada):
[[ 6.0000000e+000 -1.0000000e+000]
 [ 2.2527686e-156  1.0000000e+000]]


Iteración: 400
(matriz actualizada):
[[ 6.00000000e+000 -1.00000000e+000]
 [ 5.27796502e-312  1.00000000e+000]]


Iteración: 600
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 800
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 1000
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 1200
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 1400
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 1600
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 1800
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]


Iteración: 2000
(matriz actualizada):
[[ 6. -1.]
 [ 0.  1.]]




array([[ 0.5547002 , -0.83205029],
       [ 0.83205029,  0.5547002 ]])

In [12]:
#COMPARACION CON NUMPY
eigenvalores, eigenvectores = np.linalg.eig(B)

# Mostrar los resultados
print("Eigenvalores:")
print(eigenvalores)
print("\nEigenvectores:")
print(eigenvectores)

Eigenvalores:
[1. 6.]

Eigenvectores:
[[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]


In [13]:
Ck, QQ_c = pure_qr(C)
QQ_c

Iteración: 0
(matriz actualizada):
[[4. 3.]
 [1. 2.]]


Iteración: 200
(matriz actualizada):
[[5.00000000e+000 2.00000000e+000]
 [2.57110087e-140 1.00000000e+000]]


Iteración: 400
(matriz actualizada):
[[5.0000000e+000 2.0000000e+000]
 [4.1315998e-280 1.0000000e+000]]


Iteración: 600
(matriz actualizada):
[[5. 2.]
 [0. 1.]]


Iteración: 800
(matriz actualizada):
[[5. 2.]
 [0. 1.]]


Iteración: 1000
(matriz actualizada):
[[5. 2.]
 [0. 1.]]


Iteración: 1200
(matriz actualizada):
[[5. 2.]
 [0. 1.]]


Iteración: 1400
(matriz actualizada):
[[5. 2.]
 [0. 1.]]


Iteración: 1600
(matriz actualizada):
[[5. 2.]
 [0. 1.]]


Iteración: 1800
(matriz actualizada):
[[5. 2.]
 [0. 1.]]


Iteración: 2000
(matriz actualizada):
[[5. 2.]
 [0. 1.]]




array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [ ]:
#COMPARACION CON NUMPY
eigenvalores, eigenvectores = np.linalg.eig(C)

# Mostrar los resultados
print("Eigenvalores:")
print(eigenvalores)
print("\nEigenvectores:")
print(eigenvectores)

In [14]:
Dk, QQ_d = pure_qr(D)
QQ_d

Iteración: 0
(matriz actualizada):
[[3.33333333e+00 1.88561808e+00 4.21884749e-15]
 [1.17851130e+00 6.66666667e-01 1.22474487e+00]
 [5.77350269e-01 8.16496581e-01 1.00000000e+00]]


Iteración: 200
(matriz actualizada):
[[ 4.16424794e+000  8.81780589e-002 -6.31615086e-001]
 [ 9.88413594e-107  1.22713444e+000  7.70251267e-001]
 [ 7.80854598e-206  1.75945392e-099 -3.91382381e-001]]


Iteración: 400
(matriz actualizada):
[[ 4.16424794e+000  8.81780589e-002 -6.31615086e-001]
 [ 7.34601761e-213  1.22713444e+000  7.70251267e-001]
 [ 0.00000000e+000  9.70963425e-199 -3.91382381e-001]]


Iteración: 600
(matriz actualizada):
[[ 4.16424794e+000  8.81780589e-002 -6.31615086e-001]
 [ 5.45967242e-319  1.22713444e+000  7.70251267e-001]
 [ 0.00000000e+000  5.35831012e-298 -3.91382381e-001]]


Iteración: 800
(matriz actualizada):
[[ 4.16424794  0.08817806 -0.63161509]
 [ 0.          1.22713444  0.77025127]
 [ 0.          0.         -0.39138238]]


Iteración: 1000
(matriz actualizada):
[[ 4.16424794  0.

array([[ 0.40031591, -0.37121716, -0.83782157],
       [ 0.49644754, -0.68063221,  0.53877606],
       [ 0.77025127,  0.63161509,  0.08817806]])

In [15]:
#COMPARACION CON NUMPY
eigenvalores, eigenvectores = np.linalg.eig(D)

# Mostrar los resultados
print("Eigenvalores:")
print(eigenvalores)
print("\nEigenvectores:")
print(eigenvectores) 

Eigenvalores:
[ 4.16424794 -0.39138238  1.22713444]

Eigenvectores:
[[-0.40031591 -0.53877606 -0.38306286]
 [-0.49644754  0.83782157 -0.69522332]
 [-0.77025127 -0.08817806  0.60821655]]


In [16]:
Ek, QQ_e = pure_qr(E)
QQ_e

Iteración: 0
(matriz actualizada):
[[ 3.83333333e+00  2.59272486e+00 -8.66025404e-01]
 [ 4.71404521e-01 -3.33333333e-01 -7.09894518e-17]
 [ 2.88675135e-01  4.08248290e-01 -5.00000000e-01]]


Iteración: 200
(matriz actualizada):
[[ 4.04891734e+000  2.39475083e+000  4.98818945e-001]
 [ 1.43776605e-154 -6.92021472e-001 -1.27859767e-001]
 [ 3.26125182e-212  6.98580645e-059 -3.56895868e-001]]


Iteración: 400
(matriz actualizada):
[[ 4.04891734e+000  2.39475083e+000  4.98818945e-001]
 [ 5.17392413e-308 -6.92021472e-001 -1.27859767e-001]
 [ 0.00000000e+000  2.13111341e-116 -3.56895868e-001]]


Iteración: 600
(matriz actualizada):
[[ 4.04891734e+000  2.39475083e+000  4.98818945e-001]
 [ 0.00000000e+000 -6.92021472e-001 -1.27859767e-001]
 [ 0.00000000e+000  6.50124564e-174 -3.56895868e-001]]


Iteración: 800
(matriz actualizada):
[[ 4.04891734e+000  2.39475083e+000  4.98818945e-001]
 [ 0.00000000e+000 -6.92021472e-001 -1.27859767e-001]
 [ 0.00000000e+000  1.98329167e-231 -3.56895868e-001]]


I

array([[ 0.51769363, -0.03900114,  0.85467668],
       [ 0.74808896, -0.46410467, -0.47430977],
       [ 0.41515805,  0.88492134, -0.21108771]])

In [17]:
#COMPARACION CON NUMPY
eigenvalores, eigenvectores = np.linalg.eig(E)

# Mostrar los resultados
print("Eigenvalores:")
print(eigenvalores)
print("\nEigenvectores:")
print(eigenvectores) 

Eigenvalores:
[ 4.04891734 -0.35689587 -0.69202147]

Eigenvectores:
[[-0.51769363 -0.85467668 -0.26822309]
 [-0.74808896  0.21108771 -0.75154439]
 [-0.41515805  0.47430977  0.6026918 ]]


In [18]:
Fk, QQ_f = pure_qr(F)
QQ_f

Iteración: 0
(matriz actualizada):
[[ 4.          1.41421356 -1.15470054]
 [ 0.70710678  1.         -0.40824829]
 [ 0.57735027  0.81649658 -1.        ]]


Iteración: 200
(matriz actualizada):
[[ 4.12488542e+000  1.83902152e+000  1.03502220e+000]
 [-5.55451060e-148 -7.61557182e-001 -7.39411184e-001]
 [ 7.22787913e-163  9.90986182e-016  6.36671762e-001]]


Iteración: 400
(matriz actualizada):
[[ 4.12488542e+000  1.83902152e+000  1.03502220e+000]
 [-1.00640214e-294 -7.61557182e-001 -7.39411184e-001]
 [ 0.00000000e+000  2.74588055e-031  6.36671762e-001]]


Iteración: 600
(matriz actualizada):
[[ 4.12488542e+00  1.83902152e+00  1.03502220e+00]
 [ 0.00000000e+00 -7.61557182e-01 -7.39411184e-01]
 [ 0.00000000e+00  7.60844107e-47  6.36671762e-01]]


Iteración: 800
(matriz actualizada):
[[ 4.12488542e+00  1.83902152e+00  1.03502220e+00]
 [ 0.00000000e+00 -7.61557182e-01 -7.39411184e-01]
 [ 0.00000000e+00  2.10818987e-62  6.36671762e-01]]


Iteración: 1000
(matriz actualizada):
[[ 4.12488542e+00

array([[ 0.67550236,  0.17865763, -0.71538662],
       [ 0.61159354, -0.67770693,  0.40824829],
       [ 0.41188579,  0.71329852,  0.56705848]])

In [19]:
#COMPARACION CON NUMPY
eigenvalores, eigenvectores = np.linalg.eig(F)

# Mostrar los resultados
print("Eigenvalores:")
print(eigenvalores)
print("\nEigenvectores:")
print(eigenvectores) 

Eigenvalores:
[ 4.12488542  0.63667176 -0.76155718]

Eigenvectores:
[[-0.67550236 -0.72653358 -0.07072589]
 [-0.61159354  0.66793428 -0.84969749]
 [-0.41188579  0.16128473  0.52250553]]


In [20]:
Gk, QQ_g = pure_qr(G)
QQ_g

Iteración: 0
(matriz actualizada):
[[ 5.5         0.98198051  1.3174651   1.56524758]
 [ 1.2001984   0.97619048 -0.62822862  0.048795  ]
 [-0.09759001  0.04259177  0.02380952 -0.54554473]
 [ 1.34164079 -0.58554004 -0.32732684  1.5       ]]


Iteración: 200
(matriz actualizada):
[[ 6.09964773e+000  1.52542362e-001  6.41103498e-001  1.17035971e+000]
 [ 3.83687961e-136  1.28353694e+000 -7.64983465e-001  3.31678699e-001]
 [-3.82487504e-158  2.15785803e-023  1.00000000e+000  7.07647380e-001]
 [ 9.37258329e-241 -5.28767710e-106 -2.45042863e-083 -3.83184672e-001]]


Iteración: 400
(matriz actualizada):
[[ 6.09964773e+000  1.52542362e-001  6.41103498e-001  1.17035971e+000]
 [ 1.60214531e-271  1.28353694e+000 -7.64983465e-001  3.31678699e-001]
 [-3.32404143e-315  4.49105438e-045  1.00000000e+000  7.07647380e-001]
 [ 0.00000000e+000 -5.28708070e-211 -1.17724709e-166 -3.83184672e-001]]


Iteración: 600
(matriz actualizada):
[[ 6.09964773e+000  1.52542362e-001  6.41103498e-001  1.17035971e+000]
 [

array([[ 0.31147039,  0.41960533,  0.02253298,  0.8522968 ],
       [ 0.51244186, -0.05145287, -0.84573836, -0.13957997],
       [ 0.36253406,  0.74044997,  0.25776971, -0.50384291],
       [ 0.71341334, -0.52251106,  0.46666227, -0.01580904]])

In [21]:
#COMPARACION CON NUMPY
eigenvalores, eigenvectores = np.linalg.eig(G)

# Mostrar los resultados
print("Eigenvalores:")
print(eigenvalores)
print("\nEigenvectores:")
print(eigenvectores) 

Eigenvalores:
[ 6.09964773 -0.38318467  1.          1.28353694]

Eigenvectores:
[[ 0.31147039  0.51356051  0.37796447 -0.40953464]
 [ 0.51244186  0.2099646  -0.37796447  0.06764969]
 [ 0.36253406 -0.82668232  0.75592895 -0.72860193]
 [ 0.71341334 -0.0936313  -0.37796447  0.54483403]]


In [22]:
Hk, QQ_h = pure_qr(H)
QQ_h

Iteración: 0
(matriz actualizada):
[[ 6.4         0.8        -1.46558698 -0.34783765]
 [ 1.8        -0.4         0.20936957  0.75817737]
 [-1.83198373  0.26171196 -0.06849315 -1.09168807]
 [-0.42936209  0.21468105 -0.16855379 -0.34420116]]


Iteración: 200
(matriz actualizada):
[[ 7.17748574e+000 -3.94520684e+000  2.34347439e+000 -4.08075588e+000]
 [ 4.55895088e-090 -2.55815017e+000  9.85243001e-002 -9.08555088e-001]
 [ 0.00000000e+000  2.91888089e-304 -3.16007520e-003 -2.84626655e-001]
 [ 0.00000000e+000 -2.28532507e-305  1.94828330e-002 -6.52473972e-002]]


Iteración: 400
(matriz actualizada):
[[ 7.17748574e+000 -3.94520684e+000  3.58030781e+000 -3.05382330e+000]
 [ 1.12099696e-179 -2.55815017e+000  3.98594302e-001 -8.22375807e-001]
 [ 0.00000000e+000  0.00000000e+000  7.38449740e-002 -2.34907002e-001]
 [ 0.00000000e+000  0.00000000e+000  6.92024858e-002 -1.42252446e-001]]


Iteración: 600
(matriz actualizada):
[[ 7.17748574e+000 -3.94520684e+000  1.79707717e+000  4.34913260e+000]
 [

array([[ 0.61021998,  1.16487778,  0.1687403 ,  0.25696418],
       [ 0.50402139, -0.87309744,  0.13484976, -0.46991135],
       [ 0.59138409,  0.85225356,  0.17712143,  0.06645689],
       [ 0.4851855 , -1.18572166,  0.14323089, -0.66041864]])

In [23]:
#COMPARACION CON NUMPY
eigenvalores, eigenvectores = np.linalg.eig(H)

# Mostrar los resultados
print("Eigenvalores:")
print(eigenvalores)
print("\nEigenvectores:")
print(eigenvectores) 

Eigenvalores:
[ 6.85410197e+00 -3.41870405e-08  3.41870454e-08  1.45898034e-01]

Eigenvectores:
[[ 3.75338235e-01 -2.41738883e-08  2.41738915e-08 -9.17077354e-02]
 [ 4.30099346e-01  7.07106781e-01  7.07106781e-01 -7.20281905e-01]
 [ 5.52548911e-01 -7.07106781e-01 -7.07106781e-01  6.85252667e-01]
 [ 6.07310022e-01  1.20869437e-08 -1.20869462e-08  5.66784975e-02]]
